### PR TITLE
Add deprecation

### PR DESCRIPTION
**Pull request by rainerleber**
##### SUMMARY
This PR deprecates all modules and redirect them to the new location community.sap_libs
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
All Modules

### CODE REVIEW

**Comment by mariolenz** [comment]
Thanks @rainerleber!

I don't think the failing checks have something to do with your changes. I'm seeing a lot of `Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=fedora-37&arch=x86_64` in the `build-ansible-collection` Zuul task in several (at least two) collections at the moment :unamused: 

@felixfontein What do you think about this? I guess there should also be a changelog fragment (breaking changes?) and, in a second step, a new major release. That's more or less the original plan, isn't it?

**Comment by felixfontein** [comment]
I think for redirects there should be a new major release. There should definitely also be a changelog fragment (`deprecated_features`, and probably `major_changes` that everything is now a redirect), and the existing content should be removed

**Comment by rainerleber** [comment]
@felixfontein done :-)

**Comment by mariolenz** [comment]
Since you're redirecting modules to the `community.sap` collection, I think it might be a good idea to define it as a dependency. This might be useful for people who are using this collection directly, not via the Ansible community package.

According to the [documentation](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#structure), there's a `dependencies` key in `galaxy.yml` to do this.

**Comment by felixfontein** [comment]
LGTM

**Comment by felixfontein** [comment]
Sorry, I got interrupted and forgot to write something about adding a dependency. I think both with or without the dependency is fine - but if you don't add it, you should extend the changlog fragment to say that users have to install the other collection to be able to continue using this one. Adding it as a dependency is probably the better solution though, since it's less work for the user and for you (it's easier to add a dependency than to write extra text to explain this :D ).

**Comment by mariolenz** [comment]
@rainerleber I agree with @felixfontein, it's easier to add a dependency than to write extra text to explain this. So what do you think about adding

```
dependencies:
  "community.sap": ">=1.0.0"
```

to `galaxy.yml`?

**Comment by rainerleber** [comment]
Done wait for third party check

**Comment by mariolenz** [comment]
Cool. Thank you very much @rainerleber!

**Comment by felixfontein** [comment]
Awesome, thanks a lot!

**Pull request merged**
